### ISSUE TITLE
Dynamic = True compile causing 'SymFloat' object has no attribute size 

### ISSUE THREAD

**Issue by ali-afridi26** [chengzeyi/ParaAttention#7]
I have a general question. The script given in `examples/run_flux.py `uses parallel inference in which 1 Gpu, latents are calculated and in another GPU proper PIL image is made. Does this use Run Unified Attention (Hybird Ulysses Style and Ring Style) with torch.compile?
You mentioned in readme.md that save the Unified Attention script to` test.py `and run it as t`orchrun --nproc-per-node=2 test.py`, But how to use it for Flux Pipeline?

**Comment by ali-afridi26** [comment]
**My question is not about how to run flux.** My question is to ask if it is using the unified or not for flux and if not, how to run it for flux? Your readme says 
"A unified interface to run context parallel attention (cfg-ulysses-ring), as well as keeping the maximum performance while working with torch.compile"
**But in the table,** you have mentioned performance of **2x A100** Flux is  `para-attn (ring) + torch.compile`
and **4x** is `para-attn (ulysses + ring) + torch.compile`
Does your script `run_flux.py` with torchrun nproc 2 do unified attn or para-attn (ring) + torch.compile ?

**Comment by ali-afridi26** [comment]
Also, I am testing `run_flux.py` on multiple resolutions. Following your suggestion on #6 , using `dynamic=True` leads to the following error:` [rank0]: AttributeError: 'SymFloat' object has no attribute 'size'`

**Comment by ali-afridi26** [comment]
Alright thank you, I was a bit confused by the GPU number.
Regarding the packages, I have latest torch (2.5.1) and diffusers (0.32).
My testing code is follows:
```
import torch
import torch.distributed as dist
from diffusers import FluxPipeline
from torchao.quantization import quantize_

dist.init_process_group()
torch.set_float32_matmul_precision("high")

pipe = FluxPipeline.from_pretrained(
    "black-forest-labs/FLUX.1-dev",
    torch_dtype=torch.bfloat16,
).to(f"cuda:{dist.get_rank()}")

from para_attn.context_parallel import init_context_parallel_mesh
from para_attn.context_parallel.diffusers_adapters import parallelize_pipe

parallelize_pipe(
    pipe,
    mesh=init_context_parallel_mesh(
        pipe.device.type,
        max_ring_dim_size=2,
    ),
)

torch._inductor.config.reorder_for_compute_comm_overlap = True



# Compiling 3.3 sec
# quantize_(pipe.transformer, float8_dynamic_activation_float8_weight(granularity=PerRow()))
# quantize_(pipe.vae, float8_dynamic_activation_float8_weight(granularity=PerRow()))

pipe.transformer.to(memory_format=torch.channels_last)

pipe.transformer = torch.compile(pipe.transformer, dynamic=True, mode="max-autotune")
# pipe.vae.to(memory_format=torch.channels_last)

# pipe.vae.decode = torch.compile(pipe.vae, mode = "max-autotune-no-cudagraphs")

from time import perf_counter
count = 0
h = [1024,1152,768,1344,832,704,896,1216,1152,1408,512,1024,1728]
w = [896,1024,1344,768,1216,1408,1152,832,832,704,1024,768,1152]
while True:
        height = h[count%13]
        width =w[count%13]
    #	print("running for h",height)
    #	print("running for w",width)
        start = perf_counter()
        image = pipe(
        "A cat holding a sign that says hello world",
        num_inference_steps=28,
        height= height,
        width = width,
        output_type="pil" if dist.get_rank() == 0 else "latent",
        )[0]
        print(f"Inference Time for height{height} and width{width}",perf_counter()-start)
        count+=1
        if dist.get_rank() == 0:
            print("Saving image to flux.png")
            image[0].save("flux.png")
        if count>=26:
              break
        

dist.destroy_process_group()
```
The terminal output is attached in the text file
[out.txt](https://github.com/user-attachments/files/18062175/out.txt)

**Comment by ali-afridi26** [comment]
This looks like a pytorch issue because they added something similar to symFloat in https://github.com/pytorch/pytorch/pull/114703. Does the issue occur on your side as well?

**Comment by chengzeyi** [comment]
@ali-afridi26 You should give torch 2.5.0 a try as

**Comment by ali-afridi26** [comment]
Same error on 2.5.0

**Comment by ali-afridi26** [comment]
Even the simple flux pipeline torch compile is causing the issue:

```
import torch
from diffusers import FluxPipeline

torch.set_float32_matmul_precision("high")

pipe = FluxPipeline.from_pretrained(
    "black-forest-labs/FLUX.1-dev",
    torch_dtype=torch.bfloat16,
).to("cuda")

pipe.transformer = torch.compile(pipe.transformer, dynamic=True, mode="max-autotune-no-cudagraphs")

from time import perf_counter
while True:
        height = 1024
        width =1024
        start = perf_counter()
        image = pipe(
        "A cat holding a sign that says hello world",
        num_inference_steps=28,
        height= height,
        width = width,
        # output_type="pil" if dist.get_rank() == 0 else "latent",
        )[0]
        print("Saving image to flux.png")
        image[0].save("flux.png")

```

**Comment by ali-afridi26** [comment]
Should we raise this issue in pytorch?

**Comment by chengzeyi** [comment]
> Should we raise this issue in pytorch?

Does the stable version of diffusers have this problem？

**Comment by ali-afridi26** [comment]
No it compiled successfully on the 0.31.0 :eyes:
