### ISSUE TITLE
Could not load library libnvrtc.so.12. Error: libnvrtc.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Trgtuan10** [chengzeyi/ParaAttention#9]
I install with miniconda and have this erorr when running with Flux. 
Any idea to fix it?

conda create -n para python=3.10 
and next installation followed by Local installation

**Comment by Trgtuan10** [comment]
it also runs and returns an expected result but the time generation is so slow

**Comment by chengzeyi** [comment]
@Trgtuan10 The torch.compile compiler itself is a JIT compiler. It compiles during the first time the model is called and this is very time-consuming, meaning to measure the time generation correctly, you need to warm it up first and benchmark after the first run.

I usually don't use conda to develop. So I suggest you using the official PYPI torch to finish the installation.

**Comment by Trgtuan10** [comment]
Thankks @chengzeyi. It works for me.

**Comment by Trgtuan10** [comment]
Btw @chengzeyi , does this repo has parallel method like PiFlux?

**Comment by chengzeyi** [comment]
> Btw @chengzeyi , does this repo has parallel method like PiFlux?

Unfortunately, piflux has not been interacted into this repository by far.

**Comment by Trgtuan10** [comment]
I mean in PiFlux you use KV cache in each GPU, does para attention you use in this repo also use this method?

**Comment by chengzeyi** [comment]
> I mean in PiFlux you use KV cache in each GPU, does para attention you use in this repo also use this method? 

No, para attention works without cache and is therefore lossless.

**Comment by Trgtuan10** [comment]
Thank you so much @chengzeyi 😍
